// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProjectExists(arg1) {
  return window['go']['main']['App']['CheckProjectExists'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetEditorSettings() {
  return window['go']['main']['App']['GetEditorSettings']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetOpenRouterApiKey() {
  return window['go']['main']['App']['GetOpenRouterApiKey']();
}

export function GetStartupFiles() {
  return window['go']['main']['App']['GetStartupFiles']();
}

export function HasOpenRouterApiKey() {
  return window['go']['main']['App']['HasOpenRouterApiKey']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListProjectDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListProjectDirectory'](arg1, arg2);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ProxyURL(arg1) {
  return window['go']['main']['App']['ProxyURL'](arg1);
}

export function QueryOpenRouter(arg1, arg2) {
  return window['go']['main']['App']['QueryOpenRouter'](arg1, arg2);
}

export function ReadBinaryFile(arg1) {
  return window['go']['main']['App']['ReadBinaryFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileUnder(arg1) {
  return window['go']['main']['App']['SaveFileUnder'](arg1);
}

export function SearchInDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInDirectory'](arg1, arg2, arg3);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SetEditorSettings(arg1, arg2) {
  return window['go']['main']['App']['SetEditorSettings'](arg1, arg2);
}

export function SetInitialFiles(arg1) {
  return window['go']['main']['App']['SetInitialFiles'](arg1);
}

export function SetOpenRouterApiKey(arg1) {
  return window['go']['main']['App']['SetOpenRouterApiKey'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
