// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentProject(arg1:string,arg2:string):Promise<void>;

export function AskGeminiForSuggestions(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckProjectExists(arg1:string):Promise<boolean>;

export function CreateProject(arg1:string,arg2:string):Promise<main.ProjectConfig>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetEditorSettings():Promise<main.EditorSettings>;

export function GetGeminiApiKey():Promise<string>;

export function GetHomeDirectory():Promise<string>;

export function GetOpenRouterApiKey():Promise<string>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function GetStartupFiles():Promise<Array<string>>;

export function HasGeminiApiKey():Promise<boolean>;

export function HasOpenRouterApiKey():Promise<boolean>;

export function ListDirectory(arg1:string):Promise<main.DirectoryResult>;

export function ListProjectDirectory(arg1:string,arg2:string):Promise<main.DirectoryResult>;

export function LoadFile():Promise<main.FileResult>;

export function OpenProject(arg1:string):Promise<main.ProjectConfig>;

export function ProxyURL(arg1:string):Promise<string>;

export function QueryOpenRouter(arg1:string,arg2:string):Promise<void>;

export function ReadBinaryFile(arg1:string):Promise<main.BinaryFileResult>;

export function ReadTextFile(arg1:string):Promise<main.FileResult>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileUnder(arg1:string):Promise<main.SaveResult>;

export function SearchInDirectory(arg1:string,arg2:string,arg3:boolean):Promise<main.SearchResult>;

export function SelectProjectFolder():Promise<string>;

export function SetEditorSettings(arg1:string,arg2:number):Promise<void>;

export function SetGeminiApiKey(arg1:string):Promise<void>;

export function SetInitialFiles(arg1:Array<string>):Promise<void>;

export function SetOpenRouterApiKey(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
